/**
 * Template catalog — single source for shipped game templates.
 * Consumed by CreateProjectPage (guided creation) and LandingPage
 * (one-click launch, onboarding slice 1). Template scene data stays in
 * templateScenes.ts; this module adds display metadata + starter scripts.
 */
import { Gamepad2, Target, MessageSquare } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { templateScenes } from './templateScenes';

export interface GameTemplate {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  genre: string;
  defaultScene: any;
  defaultScript?: string;
}

export const templates: GameTemplate[] = [
  {
    id: 'platformer',
    name: 'Platformer',
    description: 'Jump between platforms, collect coins, avoid enemies',
    icon: Gamepad2,
    genre: 'action',
    defaultScene: templateScenes.platformer,
    defaultScript: [
      '// Platformer Game Script',
      'const GRAVITY = 900;',
      'const JUMP_SPEED = 450;',
      'const MOVE_SPEED = 200;',
      'let score = 0;',
      'let gameWon = false;',
      '',
      'export function update(deltaTime: number, entities: Map<string, any>, keys: Set<string>) {',
      '  const player = entities.get("player-1");',
      '  if (!player || gameWon) return;',
      '  const dt = deltaTime / 1000;',
      '',
      '  // Horizontal movement',
      '  if (keys.has("ArrowLeft") || keys.has("a")) player.vx = -MOVE_SPEED;',
      '  else if (keys.has("ArrowRight") || keys.has("d")) player.vx = MOVE_SPEED;',
      '  else player.vx *= 0.85;',
      '',
      '  // Jump',
      '  if ((keys.has("ArrowUp") || keys.has("w") || keys.has(" ")) && player.onGround) {',
      '    player.vy = -JUMP_SPEED;',
      '    player.onGround = false;',
      '  }',
      '',
      '  // Gravity',
      '  player.vy += GRAVITY * dt;',
      '  player.x += player.vx * dt;',
      '  player.y += player.vy * dt;',
      '',
      '  // Platform collision (AABB top-only landing)',
      '  player.onGround = false;',
      '  for (const [id, e] of entities) {',
      '    if (!id.startsWith("platform")) continue;',
      '    const hw = (e.collision?.width ?? e.sprite?.width ?? 80) / 2;',
      '    const hh = (e.collision?.height ?? e.sprite?.height ?? 24) / 2;',
      '    if (player.vy >= 0 &&',
      '        player.x > e.x - hw && player.x < e.x + hw &&',
      '        player.y + 24 >= e.y - hh && player.y + 24 <= e.y - hh + 16) {',
      '      player.y = e.y - hh - 24;',
      '      player.vy = 0;',
      '      player.onGround = true;',
      '    }',
      '  }',
      '',
      '  // Moving platform',
      '  const mp = entities.get("platform-moving");',
      '  if (mp?.movingPlatform) {',
      '    mp.x += mp.movingPlatform.speed * mp.movingPlatform.direction * dt;',
      '    if (Math.abs(mp.x - 380) > mp.movingPlatform.range) {',
      '      mp.movingPlatform.direction *= -1;',
      '    }',
      '  }',
      '',
      '  // Coin collection',
      '  for (const [id, e] of entities) {',
      '    if (!id.startsWith("coin")) continue;',
      '    if (Math.abs(player.x - e.x) < 20 && Math.abs(player.y - e.y) < 30) {',
      '      score += (e.collision?.value ?? 10);',
      '      entities.delete(id);',
      '    }',
      '  }',
      '',
      '  // Enemy patrol & collision',
      '  const enemy = entities.get("enemy-1");',
      '  if (enemy) {',
      '    enemy.x += enemy.ai.speed * enemy.ai.direction * dt;',
      '    if (Math.abs(enemy.x - 550) > enemy.ai.range) enemy.ai.direction *= -1;',
      '    if (Math.abs(player.x - enemy.x) < 28 && Math.abs(player.y - enemy.y) < 40) {',
      '      if (player.vy > 0 && player.y < enemy.y) {',
      '        entities.delete("enemy-1"); player.vy = -300; // stomp',
      '      } else {',
      '        player.x = 100; player.y = 350; player.vx = 0; player.vy = 0; // respawn',
      '      }',
      '    }',
      '  }',
      '',
      '  // Goal check',
      '  const goal = entities.get("goal-flag");',
      '  if (goal && Math.abs(player.x - goal.x) < 24 && Math.abs(player.y - goal.y) < 48) {',
      '    gameWon = true;',
      '    console.log("Level complete! Score:", score);',
      '  }',
      '',
      '  // Fall off screen',
      '  if (player.y > 600) { player.x = 100; player.y = 350; player.vy = 0; }',
      '}',
      '',
      'export function getHUD() {',
      '  return { score, gameWon };',
      '}',
    ].join('\n'),
  },
  {
    id: 'topdown',
    name: 'Top-Down Action',
    description: 'Move freely, fight enemies, collect items',
    icon: Target,
    genre: 'action',
    defaultScene: templateScenes.topdown,
    defaultScript: [
      '// Top-Down Action Game Script',
      'const DETECTION_RANGE = 250;',
      'let score = 0;',
      'let poweredUp = false;',
      'let powerUpTimer = 0;',
      'let health = 3;',
      '',
      'export function update(deltaTime: number, entities: Map<string, any>, keys: Set<string>) {',
      '  const player = entities.get("player-1");',
      '  if (!player || health <= 0) return;',
      '  const dt = deltaTime / 1000;',
      '  const speed = poweredUp ? 400 : 250;',
      '',
      '  // Player movement',
      '  let dx = 0, dy = 0;',
      '  if (keys.has("ArrowUp") || keys.has("w")) dy = -1;',
      '  if (keys.has("ArrowDown") || keys.has("s")) dy = 1;',
      '  if (keys.has("ArrowLeft") || keys.has("a")) dx = -1;',
      '  if (keys.has("ArrowRight") || keys.has("d")) dx = 1;',
      '  if (dx !== 0 && dy !== 0) { dx *= 0.707; dy *= 0.707; }',
      '',
      '  const nx = player.x + dx * speed * dt;',
      '  const ny = player.y + dy * speed * dt;',
      '',
      '  // Wall collision',
      '  let blockedX = false, blockedY = false;',
      '  for (const [id, e] of entities) {',
      '    if (!id.startsWith("wall")) continue;',
      '    const hw = (e.collision?.width ?? 48) / 2 + 16;',
      '    const hh = (e.collision?.height ?? 48) / 2 + 16;',
      '    if (Math.abs(nx - e.x) < hw && Math.abs(player.y - e.y) < hh) blockedX = true;',
      '    if (Math.abs(player.x - e.x) < hw && Math.abs(ny - e.y) < hh) blockedY = true;',
      '  }',
      '  if (!blockedX) player.x = nx;',
      '  if (!blockedY) player.y = ny;',
      '',
      '  // Power-up timer',
      '  if (poweredUp) {',
      '    powerUpTimer -= dt;',
      '    if (powerUpTimer <= 0) poweredUp = false;',
      '  }',
      '',
      '  // Item pickups',
      '  for (const [id, e] of [...entities]) {',
      '    if (id === "powerup-1" && Math.abs(player.x - e.x) < 24 && Math.abs(player.y - e.y) < 24) {',
      '      poweredUp = true; powerUpTimer = 5; entities.delete(id);',
      '    }',
      '    if (id === "treasure-chest" && Math.abs(player.x - e.x) < 28 && Math.abs(player.y - e.y) < 28) {',
      '      score += (e.collision?.value ?? 100); entities.delete(id);',
      '    }',
      '  }',
      '',
      '  // Enemy AI: chase when player is near',
      '  for (const [id, e] of entities) {',
      '    if (!id.startsWith("enemy")) continue;',
      '    const dist = Math.hypot(player.x - e.x, player.y - e.y);',
      '    const eSpeed = (e.ai?.speed ?? 100);',
      '    if (dist < DETECTION_RANGE) {',
      '      const angle = Math.atan2(player.y - e.y, player.x - e.x);',
      '      let enx = e.x + Math.cos(angle) * eSpeed * dt;',
      '      let eny = e.y + Math.sin(angle) * eSpeed * dt;',
      '      // Enemies also collide with walls',
      '      let eBlocked = false;',
      '      for (const [wid, w] of entities) {',
      '        if (!wid.startsWith("wall")) continue;',
      '        const hw = (w.collision?.width ?? 48) / 2 + 14;',
      '        const hh = (w.collision?.height ?? 48) / 2 + 14;',
      '        if (Math.abs(enx - w.x) < hw && Math.abs(eny - w.y) < hh) { eBlocked = true; break; }',
      '      }',
      '      if (!eBlocked) { e.x = enx; e.y = eny; }',
      '    }',
      '    // Player-enemy collision',
      '    if (dist < 26) {',
      '      if (poweredUp) { entities.delete(id); score += 50; }',
      '      else { health--; player.x = 400; player.y = 350; if (health <= 0) console.log("Game Over!"); }',
      '    }',
      '  }',
      '}',
      '',
      'export function getHUD() {',
      '  return { score, health, poweredUp };',
      '}',
    ].join('\n'),
  },
  {
    id: 'dialogue',
    name: 'Dialogue Adventure',
    description: 'Explore, talk to characters, solve quests',
    icon: MessageSquare,
    genre: 'adventure',
    defaultScene: templateScenes.dialogue,
    defaultScript: [
      '// Dialogue Adventure Game Script',
      'const INTERACT_RANGE = 60;',
      'let inventory: string[] = [];',
      'let activeDialogue: string[] | null = null;',
      'let dialogueIndex = 0;',
      'let dialogueText = "";',
      'let questComplete = false;',
      '',
      'export function update(deltaTime: number, entities: Map<string, any>, keys: Set<string>, justPressed: Set<string>) {',
      '  const player = entities.get("player-1");',
      '  if (!player) return;',
      '  const dt = deltaTime / 1000;',
      '  const speed = 150;',
      '',
      '  // If dialogue is showing, only allow advancing/closing',
      '  if (activeDialogue) {',
      '    if (justPressed.has("e") || justPressed.has("Enter")) {',
      '      dialogueIndex++;',
      '      if (dialogueIndex >= activeDialogue.length) {',
      '        activeDialogue = null; dialogueText = ""; dialogueIndex = 0;',
      '      } else {',
      '        dialogueText = activeDialogue[dialogueIndex];',
      '      }',
      '    }',
      '    return;',
      '  }',
      '',
      '  // Player movement',
      '  let dx = 0, dy = 0;',
      '  if (keys.has("ArrowUp") || keys.has("w")) dy = -1;',
      '  if (keys.has("ArrowDown") || keys.has("s")) dy = 1;',
      '  if (keys.has("ArrowLeft") || keys.has("a")) dx = -1;',
      '  if (keys.has("ArrowRight") || keys.has("d")) dx = 1;',
      '  if (dx !== 0 && dy !== 0) { dx *= 0.707; dy *= 0.707; }',
      '  player.x += dx * speed * dt;',
      '  player.y += dy * speed * dt;',
      '',
      '  // NPC collision (block movement)',
      '  for (const [id, e] of entities) {',
      '    if (!id.startsWith("npc")) continue;',
      '    if (Math.abs(player.x - e.x) < 28 && Math.abs(player.y - e.y) < 40) {',
      '      player.x -= dx * speed * dt; player.y -= dy * speed * dt;',
      '    }',
      '  }',
      '',
      '  // Interact (E key)',
      '  if (justPressed.has("e")) {',
      '    // Check NPCs',
      '    for (const [id, e] of entities) {',
      '      if (!id.startsWith("npc") || !e.dialogue) continue;',
      '      if (Math.abs(player.x - e.x) < INTERACT_RANGE && Math.abs(player.y - e.y) < INTERACT_RANGE) {',
      '        activeDialogue = e.dialogue.messages;',
      '        dialogueIndex = 0;',
      '        dialogueText = activeDialogue[0];',
      '        return;',
      '      }',
      '    }',
      '    // Check signs',
      '    for (const [id, e] of entities) {',
      '      if (!id.startsWith("sign")) continue;',
      '      if (Math.abs(player.x - e.x) < INTERACT_RANGE && Math.abs(player.y - e.y) < INTERACT_RANGE) {',
      '        activeDialogue = [e.text ?? ""];',
      '        dialogueIndex = 0;',
      '        dialogueText = activeDialogue[0];',
      '        return;',
      '      }',
      '    }',
      '    // Check locked door',
      '    const door = entities.get("locked-door");',
      '    if (door && Math.abs(player.x - door.x) < INTERACT_RANGE && Math.abs(player.y - door.y) < INTERACT_RANGE) {',
      '      if (inventory.includes("key-golden")) {',
      '        door.locked = false; door.sprite.color = "#22c55e";',
      '        activeDialogue = ["The golden key fits! The ancient door swings open..."];',
      '        dialogueIndex = 0; dialogueText = activeDialogue[0]; questComplete = true;',
      '      } else {',
      '        activeDialogue = [door.text ?? "It\\\'s locked."];',
      '        dialogueIndex = 0; dialogueText = activeDialogue[0];',
      '      }',
      '    }',
      '  }',
      '',
      '  // Key pickup',
      '  const key = entities.get("key-golden");',
      '  if (key && Math.abs(player.x - key.x) < 24 && Math.abs(player.y - key.y) < 24) {',
      '    inventory.push("key-golden");',
      '    entities.delete("key-golden");',
      '    dialogueText = "You found the Golden Key!";',
      '    activeDialogue = [dialogueText]; dialogueIndex = 0;',
      '  }',
      '}',
      '',
      'export function getHUD() {',
      '  return { inventory, dialogueText, questComplete };',
      '}',
    ].join('\n'),
  }
];

export function getTemplateById(id: string): GameTemplate | undefined {
  return templates.find((t) => t.id === id);
}
